#+Title: Well Tuned Emacs
#+Author: Роман Захаров
#+Email: zahardzhan@gmail.com

#+Options: HTML-Postamble:nil # HTML-страница без футера
#+Options: ToC:nil # Оглавление
#+Options: Org-Display-Internal-Link-With-Indirect-Buffer:t # Внутренние ссылки из этого документа открываются в другом буфере
# #+Style: <link rel="stylesheet" type="text/css" href="well-tuned-emacs.css"/>

Emacs [“Editor MACroS”, /​/ˈeditər ˈmakrōs/​/ → /​/ˈemaks/​/, далее ---
«эмакс»] был создан давным давно в Лаборатории Искуственного Интллекта
Массачусетского Технологического института
[[[https://en.wikipedia.org/wiki/MIT_Computer_Science_and_Artificial_Intelligence_Laboratory][MIT AI Lab]]]
и несет в себе черты очень своеобразной культуры лисп-хакеров былых
времен. Эмакс это текстовый редактор поведение и возможности которого
можно изменить на ходу просто написав в нем текст на языке
программирования на котором написан сам эмакс. Более того, тем же
самым способом прямо во время работы эмакса можно расширить
возможности языка программирования на котором он написан, что делает
эмакс самой гибкой и универсальной программой для работы с текстом в
сравнении с любой другой.

За несколько десятилетий своего развития эмакс несколько раз
переписывался, постоянно улучшался и дополнялся многими тысячами новых
возможностей. Когда-то эмакс был просто мощным текстовым редактором,
но сейчас это всеобъемлющая кроссплатформенная программная среда в
которой можно делать абсолютно все что угодно, если это хотя бы
немного относится к работе с простым текстом, и даже больше.

Знающим людям такая универсальность играет на руку, ведь в одной среде
можно делать тысячу разных дел не прилагая усилий для переучивания к
разным интерфейсам. Новичков подобная универсальность и непривычность
поначалу пугает. Научиться пользоваться эмаксом, понять его идею
задача непростая и долгая; однако, если есть желание, лучше начать с
общего обзора
“[[http://www.gnu.org/software/emacs/tour/][A Guided Tour of Emacs]]”
на сайте проекта
[[http://www.gnu.org/philosophy/free-sw.ru.html][свободной]]
[[http://www.gnu.org/home.ru.html][операционной системы GNU]].

История возникновения эмакса подробно описана в рассказе Столлмана
«[[http://www.gnu.org/gnu/rms-lisp.ru.html][Мой опыт работы с лиспом и развитие GNU Emacs]]»;
эта история тесно связана с очень интересной
[[http://www.gnu.org/gnu/thegnuproject.ru.html][историей проекта GNU]]
из которой можно узнать, что GNU Emacs был первой программой проекта;
однако вся суть того что из себя представляет эмакс изложена в
документе написанном в 1981 году
“[[https://www.gnu.org/software/emacs/emacs-paper.html][EMACS: The Extensible, Customizable Display Editor]]” ---
и за прошедшие более чем 35 лет эта суть ничуть не изменилась.

Расширяемость эмакса одновременно его благословение и
проклятье. Пользователь не ограничен решениями которые ему предлагают
разработчики, и если ему нужна функциональность, которой нет в эмаксе
по-умолчанию, он может добавить ее сам. Конечно, в стандартной
поставке эмакс хорош, но не так хорош как мог бы быть. Потенциально он
обладает безграничными возможностями, но чтобы ими воспользоваться
придется взяться за настройку, а это подразумевает умение
программировать и плотное общение с сообществом, активность которого
со временем только увеличивается.

Настройка эмакса это своего рода декоративно-прикладное искусство; для
каждого конкретного пользователя она заключается в составлении
лисп-программы из фрагментов лисп-кода взятых из множества
разрозненных источников. Никакого другого способа в принципе нет, и
перед тем как начать следует освоиться с программированием на лиспе
вообще и программированием на эмакс-лиспе в частности.

В изучении программирования поможет книга
«[[http://newstar.rinet.ru/~goga/sicp/sicp-ru-screen.pdf][Структура и интерпретация компьютерных программ]]» ---
это вводный курс по информатике в MIT; а в деле написания программ для
эмакса помогут учебник
«[[http://alexott.net/ru/emacs/elisp-intro/elisp-intro-ru.html][Введение в программирование на Emacs Lisp]]»
и справочник
“[[https://www.gnu.org/software/emacs/manual/html_node/elisp/index.html][GNU Emacs Lisp Reference Manual]]”.

Такое напутствие врядли пробудит энтузиазм у тех, кому текстовый
редактор нужен просто для того чтобы редактировать в нем текст; однако
часто эмакс при всей своей требовательности, полезности и практичности
становится чем-то вроде игрушки-конструктора у людей увлекающихся
программированием.

Обычно создание удобной для себя конфигурации и ее последующая доводка
растягивается на очень продолжительное время: месяцы и даже
годы. Конечно, можно облегчить себе жизнь и установить фреймворк в
котором все основные настройки выполнены в соответствии с видением
автора фреймворка, и вам даже не придется править исходный код для
того чтобы просто пользоваться эмаксом в свое удовольствие. Вот самые
популярные фреймворки на гитхабе:

- [[https://github.com/syl20bnr/spacemacs][Spacemacs]]
- [[https://github.com/bbatsov/prelude][Emacs Prelude]]
- [[https://github.com/eschulte/emacs24-starter-kit][Eschulte Literate Emacs Starter Kit]]
- [[https://github.com/overtone/emacs-live][Overtone Emacs Live]]
- [[https://github.com/purcell/emacs.d][Purcell emacs.d]]
- [[https://github.com/xiaohanyu/oh-my-emacs][Oh My Emacs]]

Все будет хорошо до тех пор пока вы не захотите встроить в эмакс некую
невероятную функциональность которой в фреймворке нет, и тогда вам
придется вручную интегрировать некий код не только с эмаксом, но и с
фреймворком, а для этого нужно будет разобраться с его внутренним
устройством, что сводит все его достоинства на нет.

К такому же выводу пришел автор одного из самых известных наборов
настроек
[[https://github.com/technomancy/emacs-starter-kit][Emacs Starter Kit]]
(см. [[http://www.google.com/search?q=meet+emacs+pluralsight+torrent][Meet Emacs]]),
когда закрывал свой проект после шести лет развития:

#+BEGIN_QUOTE
Старые версии Emacs Starter Kit были единой-для-всех кодовой базой
предназначавшейся для полной замены содержимого директории
~/.emacs.d. Это было очень популярное решение, но огромное количество
несвязанных между собой настроек вело к тому, что пользователю
приходилось просто привыкать к тому как все есть, при этом не обретая
реального понимания почему все настроенно именно таким образом. Когда
некоторые вещи ломались или вели себя непривычно, вы понятия не имели
где их исправить.

Я пришел к пониманию, что предпочтительнее использовать небольшие
пакеты дающие желаемую функциональность. Таким образом, вместо того
чтобы сваливать все настройки в одну большую кучу кода, Emacs Starter
Kit станет для вас лишь небольшим руководством. Как пользователю
Emacs, вам предстоит искать новые куски кода, настраивать их, и даже
писать свои собственные. Emacs Starter Kit поможет вам советами где
начать поиски и что именно искать, но сборка годной конфигурации это
личное дело каждого.
#+END_QUOTE

[[info:Emacs#Package][Система пакетов]] эмакса это встроенная в него [[elisp:list-packages][лисп-программа]]
которая автоматически скачивает и устанавливает другие лисп-программы,
расширяющие возможности эмакса. Система пакетов работает независимо от
операционной системы под которой запущен редактор, она сама
отслеживает зависимости между программами и заботится об обновлении
всех установленных расширений. Разработку этой ситемы
[[http://tromey.com/blog/?p=325][начал]] [[http://www.emacswiki.org/emacs/TomTromey][Том Тромей]] 
в 2007 году, в 2012 она была включена в состав Emacs 24.1, на эти годы
и пришелся пик популярности Emacs Starter Kit, то есть по большому
счету сообщество использовало его для тестирования и разработки
системы пакетов.

Как бы там ни было, личная конфигурация эмакса по своей природе была
есть и будет просто большой кучей несвязанного кода, и лучший способ
справиться с этим --- оставить все как есть; или превратить эту кучу в
руководство которое будет 
[[http://www.literateprogramming.com/knuthweb.pdf][объяснять причины]]
(в первую очередь чтобы не забыть самому) по которым тот или иной
фрагмент находится в этой куче, а потом сделать так чтобы это
руководство само превращало себя в лисп-программу и выполняло
конфигурацию эмакса при запуске. А также, по возможности, пересобирало
само себя при изменении и скачивало новые версии себя из удаленных
источников. Почему бы и нет. Это же руководство для эмакса.

*[[elisp:org-babel-tangle][Превратить это руководство в лисп-программу]]*
(/сплести/ программу --- /tangle/) очень просто, достаточно открыть его
[[https://gitlab.com/zahardzhan/well-tuned-emacs/raw/master/well-tuned-emacs.org][свежую версию]]
в эмаксе и выполнить команду [[elisp:org-babel-tangle][M-x org-babel-tangle]].
В результате из фрагментов лисп-кода в этом руководстве будет создана
[[info:Emacs#Init File][лисп-программа инициализации эмакса]] [[file:init.el][init.el]]
которую эмакс будет автоматически выполнять при каждом запуске.

----------------------------------------------------------------------

Copyright © 2010-2015 Роман Захаров [[mailto:zahardzhan@gmail.com][zahardzhan@gmail.com]].

[[https://gitlab.com/zahardzhan/well-tuned-emacs][Проект на гитлабе]] начат 1 ноября 2015.

Эта программа не является частью GNU Emacs.

Это программа является свободным программным обеспечением. Вы можете
распространять и/или модифицировать её согласно условиям
[[http://www.gnu.org/licenses/gpl-3.0.txt][Стандартной Общественной Лицензии GNU]],
опубликованной Фондом Свободного Программного Обеспечения, версии 3
или, по Вашему желанию, любой более поздней версии.

Эта программа распространяется в надежде, что она будет полезной, но
БЕЗ ВСЯКИХ ГАРАНТИЙ, в том числе подразумеваемых гарантий ТОВАРНОГО
СОСТОЯНИЯ ПРИ ПРОДАЖЕ и ГОДНОСТИ ДЛЯ ОПРЕДЕЛЁННОГО
ПРИМЕНЕНИЯ. Смотрите Стандартную Общественную Лицензию GNU для
получения дополнительной информации.

Вы должны были получить копию Стандартной Общественной Лицензии GNU
вместе с программой. В случае её отсутствия, посмотрите
[[http://www.gnu.org/licenses/][Лицензии на сайте GNU]].
