#+Title: Well Tuned Emacs
#+Author: Роман Захаров
#+Email: zahardzhan@gmail.com

#+Options: HTML-Postamble:nil # HTML-страница без футера
#+Options: ToC:nil # Оглавление
#+Options: Org-Display-Internal-Link-With-Indirect-Buffer:t # Внутренние ссылки из этого документа открываются в другом буфере
#+Options: ^:t # turn on/off TeX-like syntax for sub- and superscripts.  If
# you write "^:{}", a_{b} will be interpreted, but
# the simple a_b will be left as it is.
# #+Style: <link rel="stylesheet" type="text/css" href="well-tuned-emacs.css"/>

Emacs [“Editor MACroS”, /​/ˈeditər ˈmakrōs/​/ → /​/ˈemaks/​/, далее ---
«эмакс»] был создан давным давно в Лаборатории Искуственного Интллекта
Массачусетского Технологического института
[[[https://en.wikipedia.org/wiki/MIT_Computer_Science_and_Artificial_Intelligence_Laboratory][MIT AI Lab]]]
и несет в себе черты очень своеобразной культуры лисп-хакеров былых
времен. Эмакс это текстовый редактор поведение и возможности которого
можно изменить на ходу просто написав в нем текст на языке
программирования на котором написан сам эмакс. Более того, тем же
самым способом прямо во время работы эмакса можно расширить
возможности языка программирования на котором он написан, что делает
эмакс самой гибкой и универсальной программой для работы с текстом в
сравнении с любой другой.

За несколько десятилетий своего развития эмакс несколько раз
переписывался, постоянно улучшался и дополнялся многими тысячами новых
возможностей. Когда-то эмакс был просто мощным текстовым редактором,
но сейчас это всеобъемлющая кроссплатформенная программная среда в
которой можно делать абсолютно все что угодно, если это хотя бы
немного относится к работе с простым текстом, и даже больше.

Знающим людям такая универсальность играет на руку, ведь в одной среде
можно делать тысячу разных дел не прилагая усилий для переучивания к
разным интерфейсам. Новичков подобная универсальность и непривычность
поначалу пугает. Научиться пользоваться эмаксом, понять его идею
задача непростая и долгая; однако, если есть желание, лучше начать с
общего обзора
“[[http://www.gnu.org/software/emacs/tour/][A Guided Tour of Emacs]]”
на сайте проекта
[[http://www.gnu.org/philosophy/free-sw.ru.html][свободной]]
[[http://www.gnu.org/home.ru.html][операционной системы GNU]].

История возникновения эмакса подробно описана в рассказе Столлмана
«[[http://www.gnu.org/gnu/rms-lisp.ru.html][Мой опыт работы с лиспом и развитие GNU Emacs]]»;
эта история тесно связана с очень интересной
[[http://www.gnu.org/gnu/thegnuproject.ru.html][историей проекта GNU]]
из которой можно узнать, что GNU Emacs был первой программой проекта;
однако вся суть того что из себя представляет эмакс изложена в
документе написанном в 1981 году
“[[https://www.gnu.org/software/emacs/emacs-paper.html][EMACS: The Extensible, Customizable Display Editor]]” ---
и за прошедшие более чем 35 лет эта суть ничуть не изменилась.

Расширяемость эмакса одновременно его благословение и
проклятье. Пользователь не ограничен решениями которые ему предлагают
разработчики, и если ему нужна функциональность, которой нет в эмаксе
по-умолчанию, он может добавить ее сам. Конечно, в стандартной
поставке эмакс хорош, но не так хорош как мог бы быть. Потенциально он
обладает безграничными возможностями, но чтобы ими воспользоваться
придется взяться за настройку, а это подразумевает умение
программировать и плотное общение с сообществом, активность которого
со временем только увеличивается.

Настройка эмакса это своего рода декоративно-прикладное искусство; для
каждого конкретного пользователя она заключается в составлении
лисп-программы из фрагментов лисп-кода взятых из множества
разрозненных источников. Никакого другого способа в принципе нет, и
перед погружением в эту тему следует освоиться с программированием на
лиспе вообще и программированием на эмакс-лиспе в частности.

В изучении программирования поможет книга
«[[http://newstar.rinet.ru/~goga/sicp/sicp-ru-screen.pdf][Структура и интерпретация компьютерных программ]]» ---
это вводный курс по информатике в MIT; а в деле написания программ для
эмакса пригодится учебник
«[[http://alexott.net/ru/emacs/elisp-intro/elisp-intro-ru.html][Введение в программирование на Emacs Lisp]]»
и справочник
“[[https://www.gnu.org/software/emacs/manual/html_node/elisp/index.html][GNU Emacs Lisp Reference Manual]]”.

Такое напутствие врядли пробудит энтузиазм у тех, кому текстовый
редактор нужен только для того чтобы редактировать в нем текст; часто
эмакс при всей своей требовательности становится чем-то вроде
игрушки-конструктора у людей увлекающихся программированием.

Обычно создание удобной для себя конфигурации и ее последующая доводка
растягивается на очень продолжительное время: месяцы и даже
годы. Конечно, можно облегчить себе жизнь и установить фреймворк в
котором все основные настройки выполнены в соответствии с видением
автора фреймворка, и вам даже не придется править исходный код для
того чтобы просто пользоваться эмаксом в свое удовольствие. Вот самые
популярные фреймворки на гитхабе: [[https://github.com/syl20bnr/spacemacs][Spacemacs]],
[[https://github.com/bbatsov/prelude][Emacs Prelude]],
[[https://github.com/eschulte/emacs24-starter-kit][Eschulte Literate Emacs Starter Kit]],
[[https://github.com/overtone/emacs-live][Overtone Emacs Live]],
[[https://github.com/purcell/emacs.d][Purcell emacs.d]],
[[https://github.com/xiaohanyu/oh-my-emacs][Oh My Emacs]].

Все будет хорошо до тех пор пока вы не захотите встроить в эмакс некую
невероятную функциональность которой в фреймворке нет, и тогда вам
придется вручную интегрировать некий код не только с эмаксом, но и с
фреймворком, а для этого нужно будет разобраться с его внутренним
устройством, что сводит все его достоинства на нет.

К такому же выводу пришел автор одного из самых известных наборов
настроек
[[https://github.com/technomancy/emacs-starter-kit][Emacs Starter Kit]]
(см. [[http://www.google.com/search?q=meet+emacs+pluralsight+torrent][Meet Emacs]]),
когда закрывал свой проект после шести лет развития:

#+BEGIN_QUOTE
Старые версии Emacs Starter Kit были единой-для-всех кодовой базой
предназначавшейся для полной замены содержимого директории
~/.emacs.d. Это было очень популярное решение, но огромное количество
несвязанных между собой настроек вело к тому, что пользователю
приходилось просто привыкать к тому как все есть, при этом не обретая
реального понимания почему все настроенно именно таким образом. Когда
некоторые вещи ломались или вели себя непривычно, вы понятия не имели
где их исправить.

Я пришел к пониманию, что предпочтительнее использовать небольшие
пакеты дающие желаемую функциональность. Таким образом, вместо того
чтобы сваливать все настройки в одну большую кучу кода, Emacs Starter
Kit станет для вас лишь небольшим руководством. Как пользователю
Emacs, вам предстоит искать новые куски кода, настраивать их, и даже
писать свои собственные. Emacs Starter Kit поможет вам советами где
начать поиски и что именно искать, но сборка годной конфигурации это
личное дело каждого.
#+END_QUOTE

[[info:Emacs#Package][Система пакетов]] эмакса это встроенная в него [[elisp:list-packages][лисп-программа]]
которая автоматически скачивает и устанавливает другие лисп-программы,
расширяющие возможности эмакса. Система пакетов работает независимо от
операционной системы под которой запущен редактор, она сама
отслеживает зависимости между программами и заботится об обновлении
всех установленных расширений. Разработку этой ситемы
[[http://tromey.com/blog/?p=325][начал]] [[http://www.emacswiki.org/emacs/TomTromey][Том Тромей]] 
в 2007 году, в 2012 она была включена в состав Emacs 24.1, на эти годы
и пришелся пик популярности Emacs Starter Kit, то есть по большому
счету сообщество использовало его для тестирования и разработки
системы пакетов.

Как бы там ни было, личная конфигурация эмакса по своей природе была
есть и будет просто большой кучей несвязанного кода, и лучший способ
справиться с этим --- оставить все как есть; или превратить эту кучу в
руководство которое будет 
[[http://www.literateprogramming.com/knuthweb.pdf][объяснять причины]]
(в первую очередь чтобы не забыть самому) по которым тот или иной
фрагмент находится в этой куче, а потом сделать так чтобы это
руководство само превращало себя в лисп-программу и выполняло
конфигурацию эмакса при запуске. А также, по возможности, пересобирало
само себя при изменении и скачивало новые версии себя из удаленных
источников. Почему бы и нет. Это же руководство для эмакса.

[[elisp:org-babel-tangle][Превратить это руководство в лисп-программу]]
(/сплести/ программу --- /tangle/) очень просто, достаточно
[[https://gitlab.com/zahardzhan/well-tuned-emacs/raw/master/well-tuned-emacs.org][скачать свежую версию этого руководства из гит-репозитория]],
открыть ее в эмаксе и выполнить команду 
[[elisp:org-babel-tangle][M-x org-babel-tangle]].
В результате из фрагментов лисп-кода в этом руководстве будет создана
[[http://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html][лисп-программа инициализации эмакса]]_{🔗[[info:Emacs#Init File][info]]🔗[[http://www.emacswiki.org/emacs/InitFile][wiki]]}
[[file:init.el][init.el]]
которую эмакс будет автоматически выполнять при каждом запуске.
В общем виде программа инициализации выглядит так:

#+begin_src emacs-lisp -r -n :tangle init.el :noweb no-export
  <<essential-standard-libraries>>
  <<essential-functions>>
  <<custom-group>>
  <<custom-variables>>
  <<customize-customize-and-apply-customizations>>
  <<when-this-reference-is-not-in-user-emacs-directory-try-to-download-it>>
  (if
      <<this-reference-is-in-user-emacs-dir-and-is-newer-than-user-init-file>>
      (progn
        <<tangle-this-reference-into-user-init-file-and-then-load-it-again>>
        )
    (progn ; otherwise just continue configuration
      <<initialize-package-system-and-install-user-selected-packages>>
      <<apply-advanced-settings>>
      ))
  <<bugfixes>>
  <<provide-well-tuned-emacs>>
#+end_src

Перед написанием кода на эмакс лиспе, следует немного обновить сам
язык программирования. Эмакс лисп это древнейший из современных
лиспов, созданный в темный период между возникновением первого лиспа
как концепции теории вычислений, и первыми двумя классическими
дизайнами лиспа: Common Lisp и Scheme; сама концепция лиспа так же
стара для него, как он сам по отношению к современному Common Lisp'у,
а современный Common Lisp в свою очередь --- по отношению к
современной Clojure. Эмакс лисп старомоден, его выразительные средства
скудны, тем не менее, это полноценный лисп и он может с легкостью
дополнить свои возможности основными языковыми средствами Common Lisp,
просто выполнив относительно небольшую встроенную в эмакс
лисп-программу
[[http://www.gnu.org/software/emacs/manual/html_mono/cl.html][GNU Emacs Common Lisp Emulation]].

#+name: essential-standard-libraries
#+begin_src emacs-lisp -r -n :tangle no
  (require 'cl)
#+end_src

Файл инициализации [[file:init.el][init.el]] вторичен по отношению к этому руководству,
это не более чем автоматически сгенерированная из него программа. Но
что если руководства не окажется в директории с настройками эмакса, и
мы не сможем обновить программу инициализации? В таком случае
программа инициализации должна попытаться скачать руководство из
гит-репозитория.

#+name: when-this-reference-is-not-in-user-emacs-directory-try-to-download-it
#+begin_src emacs-lisp -r -n :tangle no
  (unless (file-exists-p well-tuned-emacs-reference-file)
    (condition-case nil
        (with-temp-file well-tuned-emacs-reference-file
          (url-insert-file-contents well-tuned-emacs-reference-url))
      (error
       (message "Failed to download %s from %s." (file-truename well-tuned-emacs-reference-file) well-tuned-emacs-reference-url)
       (when (file-exists-p well-tuned-emacs-reference-file)
         (delete-file well-tuned-emacs-reference-file 'move-to-trash)))))
#+end_src

Прежде мы должны условиться, что это руководство будет храниться в
определенном месте, по умолчанию --- в директории с личными
настройками эмакса (где бы она не находилась по данным эмакса); под
определенным именем, по-умолчанию --- well-tuned-emacs.org. Так же нам
должен быть известен адрес свежей версии этого руководства в
интернете. Для обеспечения переносимости путей файлов между разными
средами исполнения эмакс-лисп кода их следует указывать в формате
[[https://en.wikipedia.org/wiki/Path_(computing)][относительных путей POSIX]], 
это позволит использовать один-и-тот-же файл расположенный в
одном-и-том-же месте одновременно с двух запущенных в разных средах
экземпляров эмакса, к примеру, из Windows-эмакса и из Cygwin-эмакса.

#+name: custom-variables
#+begin_src emacs-lisp -r -n :tangle no
  (defcustom well-tuned-emacs-reference-file
    (concat (file-name-as-directory user-emacs-directory)
            (file-name-nondirectory "well-tuned-emacs.org"))
    "The Well Tuned Emacs Reference file."
    :type 'file
    :group 'well-tuned-emacs)

  (defcustom well-tuned-emacs-compile-user-init-file nil
    "Compile user init file after tangling from Well Tuned Emacs Reference."
    :type 'boolean
    :group 'well-tuned-emacs)

  (defcustom well-tuned-emacs-reference-url
    "https://gitlab.com/zahardzhan/well-tuned-emacs/raw/master/well-tuned-emacs.org"
    "The Well Tuned Emacs Reference File on the internet."
    :type 'string
    :group 'well-tuned-emacs)
#+end_src

Встроенное в эмакс средство
[[http://www.gnu.org/software/emacs/manual/html_node/elisp/Customization.html#Customization][Customize]]
позволит нам сделать настройки расположения файлов руководства
полностью независимыми от прописанных в этом руководстве значений
по-умолчанию. Потом эти настройки можно будет изменить в самом эмаксе
и сохранить их значения на будущее, не меняя ни фрагменты кода в этом
руководстве, ни код в сгенерированной программе инициализации init.el.

#+name: custom-group
#+begin_src emacs-lisp -r -n :tangle no
  (defgroup well-tuned-emacs nil
    "Well Tuned Emacs initialization and customization settings."
    ;:link '(emacs-commentary-link "init.el")
    ;:link '(file-link ...)
    ;:link '(url-link ...)
    :version "25.0.50.1"
    :group 'initialization)
#+end_src

Лисп-программа [[elisp:customize][M-x customize]], 
ставшая частью эмакса в середине девяностых --- это краеугольный
камень всей системы пользовательских настроек. Само это руководство
строится вокруг этой программы, ради нее оно было
написано. Парадоксально то, что подавляющее большинство фреймворков и
личных настроек отдельных людей, доступных в сети, всеми силами
избегают настройки эмакса с помощью встроенного в эмакс интерфейса
заточенного под его настройку. Люди предпочитают настраивать эмакс
написанием своего лисп-кода в тех случаях, когда этот лисп-код уже
предусмотрительно написан, отлажен и задокументирован разработчиками
лисп-программ, которые пользователь пытается настроить написанием
своего кривого и неотлаженного лисп-кода. Этот чудовищный
[[http://c2.com/cgi/wiki?NotInventedHereSyndrome][фатальный недостаток]]
распространен повсеместно и большинство пользователей эмакса считает
такое положение дел нормальным. Но это не так.

Истина состоит в том, что GNU Emacs 25 имеет 3440 стандартных
настройки в конфигурации по-умолчанию. Все они хорошо организованны,
задокументированны и доступны для поиска и изменения в простом удобном
интерфейсе Customize. Эти настроки сохраняются между сессиями эмакса,
и многие настройки лисп-программ эмакса сами выполнены в виде
специфических лисп-программ. Подключение дополнительных модулей и
пакетов расширений эмакса может запросто увеличить количество таких
настроек до десяти тысяч. К чему приведет попытка изменения нескольких
тысяч параметров управляемых лисп-кодом, меняющимся от
версии-к-версии, написанием своего лисп-кода? Она практически
неизбежно приведет к
[[http://www.emacswiki.org/emacs/DotEmacsBankruptcy][конфигурационному апокалипсису]].
Поэтому здесь и далее, и везде где только можно, я буду использовать
систему Customize.

По-умолчанию Customize хранит свои данные в файле init.el; если мы
переплетем этот файл --- все наши настройки пропадут.  В Customize
можно выполнить настройку самой Customize, но фактически программа не
может изменить место хранения своих данных, при том что такой параметр
в ней есть --- информация о том какой файл будет загружен хранится в
самом этом файле, таким образом эта информация недоступна извне. Мы
будем хранить настройки выполненные программой Customize в файле
custom.el в директории ~/.emacs.d/custom.

#+name: customize-customize-and-apply-customizations
#+begin_src emacs-lisp -r -n :tangle no
  (let ((custom-directory
         (file-name-as-directory (concat user-emacs-directory "custom"))))
    (setq custom-file (concat custom-directory "custom.el"))
    (unless (file-exists-p custom-directory)
      (make-directory custom-directory 'with-parents))
    (when (file-exists-p custom-file)
      (load custom-file)))
#+end_src

Чтобы не /переплетать/ программу инициализации эмакса вручную после
каждого редактирования этого руководства, сделаем так, что программа
будет переплетать сама себя прямо во время запуска эмакса, если
руководство было изменено после изменения программы.

#+name: this-reference-is-in-user-emacs-dir-and-is-newer-than-user-init-file
#+begin_src emacs-lisp  -r -n :tangle no
  (and (file-exists-p well-tuned-emacs-reference-file)
       (eq well-tuned-emacs-reference-file
           (file-newer-of well-tuned-emacs-reference-file user-init-file)))
#+end_src

#+name: tangle-this-reference-into-user-init-file-and-then-load-it-again
#+begin_src emacs-lisp  -r -n :tangle no
  (message "Tangling %s." well-tuned-emacs-reference-file)
  (org-babel-tangle-file well-tuned-emacs-reference-file
                         user-init-file "emacs-lisp")
  (if well-tuned-emacs-compile-user-init-file
      (progn (byte-compile-file user-init-file 'load)
             (message "Tangled, compiled and loaded %s." user-init-file))
    (progn (load user-init-file)
           (message "Tangled and loaded %s." user-init-file)))
#+end_src

Функция [[(file-newer-of)][file-newer-of]] узнает когда был изменен каждый из файлов, и
возвращает имя того файла, что был изменен позже.

#+name: essential-functions
#+begin_src emacs-lisp  -r -n :tangle no
  (defun file-newer-of (file1 file2) (ref:file-newer-of)
      "Compare last modification time of two files to each other and return FILENAME of newer file."
      (let ((difference
             (float-time
              (time-subtract (file-last-modification-time file1)
                             (file-last-modification-time file2)))))
        (cond ((> difference 0) file1)
              ((< difference 0) file2)
              ((= difference 0) nil))))
#+end_src

Время последнего изменения файла хранится в списке атрибутов файла,
который возвращает встроенная в эмакс функция
[[https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Attributes.html#File-Attributes][file-attributes]].
Для получения этой информации о файле придется написать свою
собственную функцию
[[(file-last-modification-time)][file-last-modification-time]].

#+name: essential-functions
#+begin_src emacs-lisp  -r -n :tangle no
  (defun file-last-modification-time (file) (ref:file-last-modification-time)
    "The time of last access to FILE, as a list of four integers (sec-high sec-low microsec picosec)."
    (sixth (or (file-attributes (file-truename file))
               (file-attributes file))))
#+end_src

Сама процедура сплетения файла из документа с фрагментами кода
выполянется лисп-программой [[http://orgmode.org/][Org]].

#+name: essential-standard-libraries
#+begin_src emacs-lisp  -r -n :tangle no
  (require 'org)
#+end_src

----------------------------------------------------------------------

Исправления некоторых багов GNU Emacs:

- [[http://wenshanren.org/?p=781][Emacs 25 testing: org-html-export returns org-html-fontify-code: Wrong number of arguments…]]

  #+name: bugfixes
  #+begin_src emacs-lisp -r -n :tangle no
    (defun org-font-lock-ensure ()
      (font-lock-fontify-buffer))
  #+end_src

----------------------------------------------------------------------

Copyright © 2010-2015 Роман Захаров [[mailto:zahardzhan@gmail.com][zahardzhan@gmail.com]].

[[https://gitlab.com/zahardzhan/well-tuned-emacs][Проект на гитлабе]] начат 1 ноября 2015.

Эта программа не является частью GNU Emacs.

Это программа является свободным программным обеспечением. Вы можете
распространять и/или модифицировать её согласно условиям
[[http://www.gnu.org/licenses/gpl-3.0.txt][Стандартной Общественной Лицензии GNU]],
опубликованной Фондом Свободного Программного Обеспечения, версии 3
или, по Вашему желанию, любой более поздней версии.

Эта программа распространяется в надежде, что она будет полезной, но
БЕЗ ВСЯКИХ ГАРАНТИЙ, в том числе подразумеваемых гарантий ТОВАРНОГО
СОСТОЯНИЯ ПРИ ПРОДАЖЕ и ГОДНОСТИ ДЛЯ ОПРЕДЕЛЁННОГО
ПРИМЕНЕНИЯ. Смотрите Стандартную Общественную Лицензию GNU для
получения дополнительной информации.

Вы должны были получить копию Стандартной Общественной Лицензии GNU
вместе с программой. В случае её отсутствия, посмотрите
[[http://www.gnu.org/licenses/][Лицензии на сайте GNU]].
